//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        public int leaveRequestId { get; set; }
        public int staffId { get; set; }
        public Nullable<System.DateTime> leaveDate { get; set; }
        public string type { get; set; }
        public string confirmStatus { get; set; }
        public string leaveReason { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
