//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeReceiver
    {
        public int nrId { get; set; }
        public int noticeId { get; set; }
        public int receiverId { get; set; }
        public bool isRead { get; set; }
    
        public virtual Notice Notice { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
