//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int scheduleId { get; set; }
        public int staffId { get; set; }
        public Nullable<System.DateTime> workDate { get; set; }
        public Nullable<System.TimeSpan> startWorkHour { get; set; }
        public Nullable<System.TimeSpan> endWorkHour { get; set; }
        public Nullable<bool> isHoliday { get; set; }
        public Nullable<bool> isWeekend { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
