/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 07-Jan-2020 10:46:10 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

USE [ApartmentManagement]
GO
/****** Object:  User [apiconnect]    Script Date: 12/17/2019 5:22:43 PM ******/
CREATE USER [apiconnect] FOR LOGIN [ApartmentApiConnect] WITH DEFAULT_SCHEMA=[dbo]
GO
GRANT SELECT ON SCHEMA :: [dbo] TO apiconnect
go
GRANT INSERT ON SCHEMA :: [dbo] TO apiconnect
go
GRANT UPDATE ON SCHEMA :: [dbo] TO apiconnect
go
GRANT DELETE ON SCHEMA :: [dbo] TO apiconnect
go

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Building_Complex]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Building] DROP CONSTRAINT [FK_Building_Complex]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_LeaveRequest_Staff]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [LeaveRequest] DROP CONSTRAINT [FK_LeaveRequest_Staff]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Schedule_Staff]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Schedule] DROP CONSTRAINT [FK_Schedule_Staff]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Staff_Complex]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Staff] DROP CONSTRAINT [FK_Staff_Complex]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Staff_Department]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Staff] DROP CONSTRAINT [FK_Staff_Department]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_StaffVacation_Staff]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [StaffVacation] DROP CONSTRAINT [FK_StaffVacation_Staff]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Task_Building]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Task] DROP CONSTRAINT [FK_Task_Building]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Task_Complex]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Task] DROP CONSTRAINT [FK_Task_Complex]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TaskStaff_Staff]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TaskStaff] DROP CONSTRAINT [FK_TaskStaff_Staff]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TaskStaff_Task]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TaskStaff] DROP CONSTRAINT [FK_TaskStaff_Task]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Building]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Building]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Complex]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Complex]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Department]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Department]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[LeaveRequest]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [LeaveRequest]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Schedule]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Schedule]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Staff]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Staff]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[StaffVacation]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [StaffVacation]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Task]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Task]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TaskStaff]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TaskStaff]
GO

/* Create Tables */

CREATE TABLE [Building]
(
	[buildingId] smallint NOT NULL IDENTITY (1, 1),
	[complexId] smallint NOT NULL,
	[noStaffs] smallint NOT NULL,
	[noTenants] int NOT NULL,
	[noApartments] smallint NOT NULL,
	[availApartments] smallint NOT NULL
)
GO

CREATE TABLE [Complex]
(
	[complexId] smallint NOT NULL IDENTITY (1, 1),
	[name] nvarchar(50) NOT NULL,
	[address] nvarchar(100) NOT NULL,
	[city] nvarchar(50) NOT NULL,
	[noBuildings] smallint NOT NULL,
	[contactNumber] nvarchar(10) NOT NULL
)
GO

CREATE TABLE [Department]
(
	[departmentId] smallint NOT NULL IDENTITY (1, 1),
	[name] nvarchar(50) NULL,
	[managerId] int NULL
)
GO

CREATE TABLE [LeaveRequest]
(
	[leaveRequestId] int NOT NULL,
	[staffId] int NOT NULL,
	[leaveDate] date NOT NULL,
	[type] tinyint NOT NULL,
	[confirmStatus] tinyint NOT NULL DEFAULT 0,
	[leaveReason] varchar(200) NOT NULL
)
GO

CREATE TABLE [Schedule]
(
	[scheduleId] int NOT NULL IDENTITY (1, 1),
	[staffId] int NOT NULL,
	[wordDate] date NOT NULL,
	[startWorkHour] time(7) NOT NULL,
	[endWorkHour] time(7) NOT NULL,
	[isHoliday] bit NOT NULL DEFAULT 0,
	[isWeekend] bit NOT NULL DEFAULT 0
)
GO

CREATE TABLE [Staff]
(
	[staffId] int NOT NULL IDENTITY (1, 1),
	[departmentId] smallint NOT NULL,
	[complexId] smallint NOT NULL,
	[name] varchar(100) NOT NULL,
	[birthday] date NOT NULL,
	[address] nvarchar(100) NOT NULL,
	[city] nvarchar(50) NOT NULL,
	[mobile] nvarchar(10) NOT NULL,
	[joinDate] date NOT NULL,
	[leaveDate] date NULL
)
GO

CREATE TABLE [StaffVacation]
(
	[staffVacationId] int NOT NULL IDENTITY (1, 1),
	[staffId] int NOT NULL,
	[maxVacationDay] tinyint NULL,
	[usedDay] tinyint NULL
)
GO

CREATE TABLE [Task]
(
	[taskId] int NOT NULL IDENTITY (1, 1),
	[taskType] smallint NOT NULL,
	[taskStatus] smallint NOT NULL DEFAULT 0,
	[priority] smallint NOT NULL DEFAULT 1,
	[complexId] smallint NOT NULL,
	[buildingId] smallint NOT NULL,
	[startDate] datetime NOT NULL,
	[endDate] datetime NULL,
	[description] nvarchar(200) NOT NULL,
	[cost] money NOT NULL DEFAULT 0
)
GO

CREATE TABLE [TaskStaff]
(
	[taskId] int NOT NULL,
	[staffId] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Building] 
 ADD CONSTRAINT [PK_Building]
	PRIMARY KEY CLUSTERED ([buildingId] ASC)
GO

ALTER TABLE [Complex] 
 ADD CONSTRAINT [PK_Complex]
	PRIMARY KEY CLUSTERED ([complexId] ASC)
GO

ALTER TABLE [Department] 
 ADD CONSTRAINT [PK_Department]
	PRIMARY KEY CLUSTERED ([departmentId] ASC)
GO

ALTER TABLE [LeaveRequest] 
 ADD CONSTRAINT [PK_LeaveRequest]
	PRIMARY KEY CLUSTERED ([leaveRequestId] ASC)
GO

ALTER TABLE [Schedule] 
 ADD CONSTRAINT [PK_Schedule]
	PRIMARY KEY CLUSTERED ([scheduleId] ASC)
GO

ALTER TABLE [Staff] 
 ADD CONSTRAINT [PK_Staff]
	PRIMARY KEY CLUSTERED ([staffId] ASC)
GO

ALTER TABLE [StaffVacation] 
 ADD CONSTRAINT [PK_StaffVacation]
	PRIMARY KEY CLUSTERED ([staffVacationId] ASC)
GO

ALTER TABLE [Task] 
 ADD CONSTRAINT [PK_Task]
	PRIMARY KEY CLUSTERED ([taskId] ASC)
GO

ALTER TABLE [TaskStaff] 
 ADD CONSTRAINT [PK_TaskStaff]
	PRIMARY KEY CLUSTERED ([taskId] ASC,[staffId] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Building] ADD CONSTRAINT [FK_Building_Complex]
	FOREIGN KEY ([complexId]) REFERENCES [Complex] ([complexId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [LeaveRequest] ADD CONSTRAINT [FK_LeaveRequest_Staff]
	FOREIGN KEY ([staffId]) REFERENCES [Staff] ([staffId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Schedule] ADD CONSTRAINT [FK_Schedule_Staff]
	FOREIGN KEY ([staffId]) REFERENCES [Staff] ([staffId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Staff] ADD CONSTRAINT [FK_Staff_Complex]
	FOREIGN KEY ([complexId]) REFERENCES [Complex] ([complexId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Staff] ADD CONSTRAINT [FK_Staff_Department]
	FOREIGN KEY ([departmentId]) REFERENCES [Department] ([departmentId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [StaffVacation] ADD CONSTRAINT [FK_StaffVacation_Staff]
	FOREIGN KEY ([staffId]) REFERENCES [Staff] ([staffId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Task] ADD CONSTRAINT [FK_Task_Building]
	FOREIGN KEY ([buildingId]) REFERENCES [Building] ([buildingId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Task] ADD CONSTRAINT [FK_Task_Complex]
	FOREIGN KEY ([complexId]) REFERENCES [Complex] ([complexId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [TaskStaff] ADD CONSTRAINT [FK_TaskStaff_Staff]
	FOREIGN KEY ([staffId]) REFERENCES [Staff] ([staffId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [TaskStaff] ADD CONSTRAINT [FK_TaskStaff_Task]
	FOREIGN KEY ([taskId]) REFERENCES [Task] ([taskId]) ON DELETE No Action ON UPDATE No Action
GO
