USE [master]
GO
CREATE LOGIN [ApartmentApiConnect] WITH PASSWORD=N'123456', DEFAULT_DATABASE=[ApartmentManagement], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER LOGIN [ApartmentApiConnect] ENABLE
GO