//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public short buildingId { get; set; }
        public short complexId { get; set; }
        public short noStaffs { get; set; }
        public int noTenants { get; set; }
        public short noApartments { get; set; }
        public short availApartments { get; set; }
    
        public virtual Complex Complex { get; set; }
    }
}
