//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplexApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public short complexId { get; set; }
        public short buildingNum { get; set; }
        public Nullable<short> numOfStaff { get; set; }
        public Nullable<int> numOfTenant { get; set; }
        public Nullable<int> numOfDepartment { get; set; }
        public Nullable<int> availApartment { get; set; }
    
        public virtual Complex Complex { get; set; }
    }
}
