//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskStaffs = new HashSet<TaskStaff>();
        }
    
        public int taskId { get; set; }
        public short taskTypeId { get; set; }
        public string taskStatus { get; set; }
        public Nullable<short> priority { get; set; }
        public Nullable<short> complexId { get; set; }
        public Nullable<short> buildingNum { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string description { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual TaskType TaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskStaff> TaskStaffs { get; set; }
    }
}
